### ISSUE TITLE
Upgrade the Rake Gem to latest Version

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/learn_ruby#28]
We've had a [report](https://forum.theodinproject.com/t/first-ruby-project-00-hello-rake-aborted-windows/3090/8) about rake not working for this project on windows. The student who reported the issue discovered the solution was to upgrade the rake gem as version 11 has a dependency on a unix library thus stoping rake tasks from running.

**Comment by Deetss** [comment]
Ill take this! @KevinMulhern

**Comment by KevinMulhern** [comment]
It's all yours @Deetss, thank you for taking it on 😄

**Comment by Deetss** [comment]
Fixed in Commit 48a0c098ec817af8659815da2a436d7e7be9c8c6

**Comment by KevinMulhern** [comment]
solved in https://github.com/TheOdinProject/learn_ruby/pull/29
